customhost ="insurance-database.cygb7l0fmtuj.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "adminadmin"
customdb = "insurance"
custombucket = "insuranceproject001"
customregion = "Asia Pacific (Mumbai) ap-south-1"
